### ISSUE TITLE
Matching of strings with numerical characters doesn't work

### ISSUE THREAD

**Issue by bandreghetti** [jhvst/go-jaro-winkler-distance#1]
```
jwd.Calculate("349398", "234567") // -0.1111...
jwd.Calculate("234567", "349398") // 0.1111...
```

Jaro-Winkler should return values from 0 to 1.

**Comment by jhvst** [comment]
I agree that negative values should not be returned. This was fixed today: https://github.com/jhvst/go-jaro-winkler-distance/commit/32671379e37c6b904152db948dc3ec96335e81fc
